import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Providers from '@/store/queryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import useAuthStore from '@/store/useAuthStore';
import SideBar from './_components/SideBar';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900'
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900'
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export type Props = { points: 0; setPoints: (value: number) => void };

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
<<<<<<< HEAD
          <SideBar />
          {children}
=======
          <CookiesProvider>
            <div className="flex flex-row">
              <SideBar />
              {children}
            </div>
          </CookiesProvider>
>>>>>>> a64f49e63829e20ae0c74d16e9daeca18b61ffca
          <ReactQueryDevtools />
        </Providers>
      </body>
    </html>
  );
}
